### ISSUE TITLE
Plugin broken 

### ISSUE THREAD

**Issue by test124-mc** [FroobWorld/NabSuite#9]
this  log i want this plugin since i read docs on wiki and i cant play froobworld since i am banned 

                                                [EU5-Free Daemon]: Checking server disk space usage, this could take a few seconds...
[EU5-Free Daemon]: Updating process configuration files...
[EU5-Free Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
[EU5-Free Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[EU5-Free Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -Xms128M -Xmx3072M -Dpaper.playerconnection.keepalive=60 -Dfile.encoding=UTF-8 -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
Starting org.bukkit.craftbukkit.Main
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads/paper ***
[18:26:03 INFO]: [bootstrap] Running Java 21 (OpenJDK 64-Bit Server VM 21.0.5+11-LTS; Eclipse Adoptium Temurin-21.0.5+11) on Linux 5.15.0-113-generic (amd64)
[18:26:03 INFO]: [bootstrap] Loading Nabulus 1.21.1-67-HEAD@91ef12c (2024-10-26T21:33:07Z) for Minecraft 1.21.1
[18:26:04 INFO]: [PluginInitializerManager] Initializing plugins...
[18:26:04 ERROR]: [DirectoryProviderSource] Error loading plugin: java.lang.IllegalArgumentException: plugins/.paper-remapped/nabulus-paperclip-1.21.1-R0.1-SNAPSHOT-mojmap.jar appears to be a server jar! Server jars do not belong in the plugin folder.
java.lang.RuntimeException: java.lang.IllegalArgumentException: plugins/.paper-remapped/nabulus-paperclip-1.21.1-R0.1-SNAPSHOT-mojmap.jar appears to be a server jar! Server jars do not belong in the plugin folder.
	at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:82) ~[nabulus-1.21.1.jar:1.21.1-67-91ef12c]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:52) ~[nabulus-1.21.1.jar:1.21.1-67-91ef12c]
	at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[nabulus-1.21.1.jar:1.21.1-67-91ef12c]
	at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[nabulus-1.21.1.jar:1.21.1-67-91ef12c]
	at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:113) ~[nabulus-1.21.1.jar:1.21.1-67-91ef12c]
	at net.minecraft.server.Main.main(Main.java:123) ~[nabulus-1.21.1.jar:1.21.1-67-91ef12c]
	at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[nabulus-1.21.1.jar:1.21.1-67-91ef12c]
	at org.bukkit.craftbukkit.Main.main(Main.java:281) ~[nabulus-1.21.1.jar:1.21.1-67-91ef12c]
	at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: plugins/.paper-remapped/nabulus-paperclip-1.21.1-R0.1-SNAPSHOT-mojmap.jar appears to be a server jar! Server jars do not belong in the plugin folder.
	... 10 more
[18:26:04 INFO]: [PluginInitializerManager] Initialized 0 plugins
[18:26:12 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[18:26:14 INFO]: Loaded 1290 recipes
[18:26:14 INFO]: Loaded 1399 advancements
[18:26:15 INFO]: Starting minecraft server version 1.21.1
[18:26:15 INFO]: Loading properties
[18:26:15 INFO]: This server is running Nabulus version 1.21.1-67-HEAD@91ef12c (2024-10-26T21:33:07Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
[18:26:16 INFO]: [spark] This server bundles the spark profiler. For more information please visit https://docs.papermc.io/paper/profiling
[18:26:16 INFO]: Using 4 threads for Netty based IO
[18:26:16 INFO]: Server Ping Player Sample Count: 12
[18:26:17 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and population gen parallelism of 1 threads
[18:26:18 WARN]: [Pufferfish] SIMD operations are available for your server, but are not configured!
[18:26:18 WARN]: [Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[18:26:18 WARN]: [Pufferfish] If you have already added this flag, then SIMD operations are not supported on your JVM or CPU.
[18:26:18 WARN]: [Pufferfish] Debug: Java: 21.0.5, test run: true
[18:26:18 INFO]: Default game type: SURVIVAL
[18:26:18 INFO]: Generating keypair
[18:26:18 INFO]: Starting Minecraft server on 0.0.0.0:42946
[18:26:18 INFO]: Using epoll channel type
[18:26:18 INFO]: Paper: Using libdeflate (Linux x86_64, musl) compression from Velocity.
[18:26:18 INFO]: Paper: Using OpenSSL 3.x.x (Linux x86_64, musl) cipher from Velocity.
[18:26:18 INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:26:18 INFO]: Preparing level "world"
[18:26:19 INFO]: Preparing start region for dimension minecraft:overworld
[18:26:21 INFO]: Time elapsed: 2034 ms
[18:26:21 INFO]: Preparing start region for dimension minecraft:the_nether
[18:26:22 INFO]: Time elapsed: 299 ms
[18:26:22 INFO]: Preparing start region for dimension minecraft:the_end
[18:26:22 INFO]: Time elapsed: 219 ms
[18:26:22 INFO]: [spark] Starting background profiler...
[18:26:22 INFO]: Done preparing level "world" (4.097s)
[18:26:22 INFO]: Running delayed init tasks
[18:26:22 INFO]: Done (20.387s)! For help, type "help"
[18:26:22 INFO]: Timings Reset

**Comment by froobynooby** [comment]
You're using the jar for Nabulus not NabSuite
